/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccordionContent: typeof import('radix-vue')['AccordionContent']
    AccordionHeader: typeof import('radix-vue')['AccordionHeader']
    AccordionItem: typeof import('radix-vue')['AccordionItem']
    AccordionRoot: typeof import('radix-vue')['AccordionRoot']
    AccordionTrigger: typeof import('radix-vue')['AccordionTrigger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
